import Head from 'next/head'

const About = () => {
  return (
    <>
      <Head>
        {/* eslint-disable-next-line */}
        <title>Who am I ?</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

export default About
