import { GetStaticProps } from 'next'
import Head from 'next/head'

import { getAllDesigns } from '../lib/graphcms'

import Hero from '../components/Hero'
import Featured from '../components/Featured'

interface Props {
  title: string
  id: string
  design_img: {
    url: string
  }
}

const Home = ({ designs }: { designs: Props[] }) => {
  return (
    <div>
      <Head>
        {/* eslint-disable-next-line */}
        <title>Momen's Gallery</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Featured designs={designs} />
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const designs = await getAllDesigns()

  return {
    props: {
      designs,
    },
  }
}
